- hosts: targets
  user: vagrant
  become: yes
  tasks:
    - name: register cron job  
      cron: name="check ping" day="*/2" hour="12" minute="0" job="ping -c 3 192.168.100.10"

  roles:
    - role-common
    - role-web
